"""Per-user auto-start registration for SpyStroke bots.

Registers the supervisor so it launches when the machine boots, without
requiring administrator rights:

* **Windows** — writes a VBS launcher into the user's Startup folder
  (``%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup``). The
  launcher runs the supervisor hidden with ``pythonw``.
* **Linux** — writes a systemd *user* unit into
  ``~/.config/systemd/user`` and enables it.  Optionally enables user
  lingering so the service starts at boot even before login.
* **macOS** — writes a launchd LaunchAgent plist into
  ``~/Library/LaunchAgents`` with ``RunAtLoad`` + ``KeepAlive``.

All functions take an explicit ``platform`` argument (defaulting to the
current one) and accept overridable paths, which keeps them unit-testable
without touching the real system.
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Callable, Optional

logger = logging.getLogger("spystroke.autostart")

#: The module the launchers execute. Must be importable from the repo root.
SUPERVISOR_MODULE = "spystroke.supervisor"

#: Sentinel used to swallow expected errors from best-effort commands.
_Command = Callable[[list[str]], None]


def repo_root() -> Path:
    """Absolute path of the repository root (parent of the package)."""
    return Path(__file__).resolve().parent.parent


def _default_run(command: list[str]) -> None:
    """Run a shell command, logging failures without raising."""
    try:
        result = subprocess.run(
            command, capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            logger.warning(
                "Command %r exited %d: %s",
                " ".join(command),
                result.returncode,
                (result.stderr or result.stdout).strip(),
            )
    except FileNotFoundError:
        logger.warning("Command not found: %s", command[0])
    except subprocess.TimeoutExpired:
        logger.warning("Command timed out: %s", " ".join(command))


def _windows_startup_dir(home: Path, appdata: Optional[str]) -> Path:
    base = Path(appdata) if appdata else home / "AppData" / "Roaming"
    return base / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"


def _windows_launcher(name: str, root: Path, python_exe: Path) -> str:
    """VBScript that runs the supervisor hidden at boot."""
    pythonw = python_exe
    if python_exe.name.lower() == "python.exe":
        candidate = python_exe.with_name("pythonw.exe")
        if candidate.exists():
            pythonw = candidate

    def vbs_quote(value: str) -> str:
        return value.replace('"', '""')

    return (
        "' SpyStroke auto-start launcher (generated by spystroke.autostart)\r\n"
        "Set shell = CreateObject(\"WScript.Shell\")\r\n"
        f"shell.CurrentDirectory = \"{vbs_quote(str(root))}\"\r\n"
        f"shell.Run \"\"\"{vbs_quote(str(pythonw))}\"\"\" -m {SUPERVISOR_MODULE} run {name}\", 0, False\r\n"
    )


def _systemd_unit(name: str, root: Path, python_exe: Path) -> str:
    """systemd user unit that keeps the supervisor (and bot) alive."""
    return (
        "[Unit]\n"
        f"Description=SpyStroke {name} bot (supervised)\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"WorkingDirectory={root}\n"
        f"ExecStart={python_exe} -m {SUPERVISOR_MODULE} run {name}\n"
        "Restart=always\n"
        "RestartSec=5\n"
        "Environment=PYTHONUNBUFFERED=1\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def _launchd_plist(name: str, root: Path, python_exe: Path, log_file: Path) -> str:
    """launchd LaunchAgent plist with RunAtLoad + KeepAlive."""
    log_file.parent.mkdir(parents=True, exist_ok=True)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        "<dict>\n"
        f"    <key>Label</key>\n    <string>com.spystroke.{name}</string>\n"
        "    <key>ProgramArguments</key>\n"
        "    <array>\n"
        f"        <string>{python_exe}</string>\n"
        f"        <string>-m</string>\n"
        f"        <string>{SUPERVISOR_MODULE}</string>\n"
        f"        <string>run</string>\n"
        f"        <string>{name}</string>\n"
        "    </array>\n"
        f"    <key>WorkingDirectory</key>\n    <string>{root}</string>\n"
        "    <key>RunAtLoad</key>\n    <true/>\n"
        "    <key>KeepAlive</key>\n    <true/>\n"
        f"    <key>StandardOutPath</key>\n    <string>{log_file}</string>\n"
        f"    <key>StandardErrorPath</key>\n    <string>{log_file}</string>\n"
        "</dict>\n"
        "</plist>\n"
    )


def _autostart_target(
    name: str,
    *,
    platform: str,
    home: Path,
    appdata: Optional[str],
) -> Path:
    """Path of the auto-start artifact for this platform."""
    if platform == "win32":
        return _windows_startup_dir(home, appdata) / f"spystroke-{name}.vbs"
    if platform == "linux":
        return home / ".config" / "systemd" / "user" / f"spystroke-{name}.service"
    if platform == "darwin":
        return home / "Library" / "LaunchAgents" / f"com.spystroke.{name}.plist"
    raise NotImplementedError(f"Auto-start is not supported on platform {platform!r}")


def install_autostart(
    name: str,
    *,
    platform: str = sys.platform,
    home: Optional[Path] = None,
    appdata: Optional[str] = None,
    root: Optional[Path] = None,
    python_exe: Optional[Path] = None,
    run: _Command = _default_run,
) -> Path:
    """Register *name* to start automatically at boot.

    Returns the path of the generated artifact.
    """
    home = home or Path.home()
    root = root or repo_root()
    python_exe = python_exe or Path(sys.executable)
    target = _autostart_target(name, platform=platform, home=home, appdata=appdata)

    if platform == "win32":
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            _windows_launcher(name, root, python_exe), encoding="utf-8"
        )
        logger.info("Wrote Windows startup launcher: %s", target)

    elif platform == "linux":
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_systemd_unit(name, root, python_exe), encoding="utf-8")
        unit = target.name
        run(["systemctl", "--user", "daemon-reload"])
        run(["systemctl", "--user", "enable", "--now", unit])
        # Best effort: start the service at boot even without a login session.
        run(["loginctl", "enable-linger", os.environ.get("USER", "")])
        logger.info("Installed and enabled systemd user unit: %s", target)

    elif platform == "darwin":
        target.parent.mkdir(parents=True, exist_ok=True)
        log_file = home / ".spystroke" / f"spystroke-{name}.log"
        target.write_text(
            _launchd_plist(name, root, python_exe, log_file), encoding="utf-8"
        )
        run(["launchctl", "load", "-w", str(target)])
        logger.info("Loaded LaunchAgent: %s", target)

    else:  # pragma: no cover - handled by _autostart_target
        raise NotImplementedError(f"Unsupported platform: {platform!r}")

    return target


def uninstall_autostart(
    name: str,
    *,
    platform: str = sys.platform,
    home: Optional[Path] = None,
    appdata: Optional[str] = None,
    run: _Command = _default_run,
) -> bool:
    """Remove the auto-start registration for *name*. Returns True if removed."""
    home = home or Path.home()
    target = _autostart_target(name, platform=platform, home=home, appdata=appdata)

    if platform == "linux" and target.exists():
        run(["systemctl", "--user", "disable", "--now", target.name])
    elif platform == "darwin" and target.exists():
        run(["launchctl", "unload", "-w", str(target)])

    if target.exists():
        try:
            target.unlink()
        except OSError as exc:  # pragma: no cover - defensive
            logger.warning("Could not remove %s: %s", target, exc)
            return False
        logger.info("Removed auto-start registration: %s", target)
        return True
    return False


def autostart_installed(
    name: str,
    *,
    platform: str = sys.platform,
    home: Optional[Path] = None,
    appdata: Optional[str] = None,
) -> bool:
    """Return True if *name* is registered to start automatically."""
    home = home or Path.home()
    target = _autostart_target(name, platform=platform, home=home, appdata=appdata)
    return target.exists()
